server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    max-threads: 200
    accept-count: 100
    max-connections: 10000
    connection-timeout: 20000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.96.28:3306/task-list?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: f9c9b5f92dbfbefb
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.com.tasklist.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.com.tasklist: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
    org.mybatis: DEBUG 